### ISSUE TITLE
Errors after upgrading from 1.8 to 1.9

### ISSUE THREAD

**Issue by grsmvg** [ReactTraining/react-media#111]
I get a bunch of runtime errors with version 1.9.0

```
Error: Cannot find module "@babel/runtime/helpers/esm/inheritsLoose"

Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/assertThisInitialized' in ...

Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/defineProperty' in ...

Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/inheritsLoose' in ...
```

**Comment by edorivai** [comment]
I'm seeing the same in an older project of mine, though I get them at compile time.

I'm pretty sure the root cause is that with our current rollup setup, the esm bundle depends on `@babel/runtime`, while this is not added as a (peer)dependency. Looking into this :eyes:

**Comment by kevva** [comment]
The new release also causes tests to fail unless you manually set `__DEV__` globally. Not ideal.

**Comment by sarabs3** [comment]
I am also getting `ReferenceError: __DEV__ is not defined` error.

**Comment by spartDev** [comment]
I made a PR #112 for `ReferenceError: __DEV__ is not defined`

**Comment by wellyal** [comment]
waiting for the fix...

**Comment by wellyal** [comment]
I am also getting ReferenceError: __DEV__ is not defined error.

**Comment by wellyal** [comment]
Can anyone make a patch release out of #112 please?

**Comment by edorivai** [comment]
#112 is merged, which should fix the `__DEV__ is not defined` errors. Please upgrade to `1.9.1` to get the patch.

Regarding the `@babel/runtime` errors, I'm still looking at a proper fix, there are a couple things to consider here. In the meantime you can either switch back to 1.8.0, or install `@babel/runtime` manually into your project.

**Comment by iamtchelo** [comment]
Thanks @edorivai =)

**Comment by edorivai** [comment]
@grsmvg I've opened #113 to fix the `@babel/runtime` dependency issue. I want to give @mjackson some time provide feedback before merging. However, if he's doesn't have the time to review, I'll merge it some time next week :smile:.

**Comment by grsmvg** [comment]
Great! The safari bug is just a warning, that won't crash in production, so i'll just stick to 1.8.0 for now :)

**Comment by mjackson** [comment]
Hey everyone, sorry for the bad release. [Version 1.9.2 should be published shortly](https://travis-ci.org/ReactTraining/react-media/builds/467131383) which fixes both the `__DEV__` issue and the missing dependency.

**Comment by plainnany** [comment]
hello，version 1.9.2 still has errors 
```
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/defineProperty' in '/cloud/source_code/node_modules/_react-media@1.9.2@react-media/esm'
```

**Comment by edorivai** [comment]
@plainnany :thinking: 1.9.2 is working in my project. Would you mind creating a replication repo for me to take a look at?
